fix: Clear the child of the saved specs before clearing them
NativeScript/tns-core-modules-widgets pull request #131
Opened 2018-07-27 14:52 UTC by VladimirAmiorkov

## PR Checklist

- [X] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [X] You have signed the [CLA](http://www.nativescript.org/cla). 
- [X] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?
After adding a NativeScript `View` manually by calling `_addView()` in `RadListView`, calling `_removeView()` does not clear all of the references to that `View` and causes memory leak.

## What is the new behavior?
Calling `_removeView()` after manually adding a `View` via `_addView()` does not cause any `View` to be retained in the memory.

Fixes/Implements/Closes #[Issue Number].

Related to issue: https://github.com/telerik/nativescript-ui-feedback/issues/748

2018-07-30 08:20 UTC, ADjenkov requested changes

2018-07-30 08:20 UTC, ADjenkov commented on android/widgets/src/main/java/org/nativescript/widgets/GridLayout.java
> +        this.map.get(child).child = null;;
Multiple ';'

2018-07-30 08:33 UTC, VladimirAmiorkov commented on android/widgets/src/main/java/org/nativescript/widgets/GridLayout.java
> +        this.map.get(child).child = null;;
Ooo wow, I will fix it :)

2018-07-31 08:05 UTC, vakrilov commented
Related to https://github.com/NativeScript/NativeScript/issues/6111

2018-08-06 10:32 UTC, MartoYankov approved these changes

2018-08-23 13:20 UTC, NathanaelA commented
@vakrilov @MartoYankov @ADjenkov - Can we get this merged so that it can be tested out in a @next build; right now this is causing one of my clients a lot of pain from the memory leak it is causing in a RLV.

2018-08-23 13:24 UTC, ADjenkov approved these changes

2018-08-24 14:04 UTC, merged

2018-08-24 14:08 UTC, VladimirAmiorkov commented
HI @NathanaelA ,

The PR is merged and is available in the **@next** version (4.3.0-2018-08-24-01)

2018-08-24 15:19 UTC, NathanaelA commented
@VladimirAmiorkov - Thank you!